### ISSUE TITLE
Unable to install Spina on a fresh Rails 5.0.0 app

### ISSUE THREAD

**Issue by erlingur** [denkGroot/Spina#179]
```
23:27:23 ~/Projects/ms (master*)$ rails g spina:install
/Users/eth/.rvm/gems/ruby-2.3.1@ms/gems/breadcrumbs_on_rails-2.3.1/lib/breadcrumbs_on_rails/action_controller.rb:16:in `block in <module:ActionController>': undefined method `helper' for ActionController::API:Class (NoMethodError)
    from /Users/eth/.rvm/gems/ruby-2.3.1@ms/gems/activesupport-5.0.0/lib/active_support/concern.rb:120:in `class_eval'
    from /Users/eth/.rvm/gems/ruby-2.3.1@ms/gems/activesupport-5.0.0/lib/active_support/concern.rb:120:in `append_features'
    from /Users/eth/.rvm/gems/ruby-2.3.1@ms/gems/breadcrumbs_on_rails-2.3.1/lib/breadcrumbs_on_rails/railtie.rb:14:in `include'
    from /Users/eth/.rvm/gems/ruby-2.3.1@ms/gems/breadcrumbs_on_rails-2.3.1/lib/breadcrumbs_on_rails/railtie.rb:14:in `block (2 levels) in <class:Railtie>'
    from /Users/eth/.rvm/gems/ruby-2.3.1@ms/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
    from /Users/eth/.rvm/gems/ruby-2.3.1@ms/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
<...snip...>
```

Rails 5.0.0 running on Ruby 2.3.1 on macOS Sierra.

Same as here: https://github.com/weppos/breadcrumbs_on_rails/issues/82

**Comment by courtneygives** [comment]
If I fix my version of Spina at 0.9 and my rails version at 5 when I run bundle install I get the following. Probably related?

```
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies.....
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    spina (~> 0.9) was resolved to 0.9.0, which depends on
      globalize (~> 5.0.0) was resolved to 5.0.0, which depends on
        activerecord (< 4.3, >= 4.2.0)

    rails (~> 5) was resolved to 5.0.0, which depends on
      activerecord (= 5.0.0)
```

**Comment by alexives** [comment]
I'm experiencing the same thing on Ruby 2.2.5 on macOS El Capitan

**Comment by Bramjetten** [comment]
Can you try using the master branch? Spina 0.9.0 isn't ready for Rails 5.

**Comment by Bramjetten** [comment]
Also, don't forget to add gem 'globalize', github: 'globalize/globalize' to your Gemfile.

**Comment by andrewgy8** [comment]
I thought I would post this hear since I would have a similar title.  And I apologize ahead of time as I am kind of new to this.  But I have been banging my head on the wall for the past 3 hours and cant figure out the issue.  

In my gemfile on a fresh rails 5.0 app, I have:
gem 'spina-template'
gem 'spina'
gem 'globalize', github: 'globalize/globalize'


When I boot local server and go to localhost:3000/admin, I receive this error:

Sass::SyntaxError in Spina::Admin::Sessions#new
".new_document .customfile:after" failed to @extend ".fa-refresh".
No selectors matching ".fa-refresh" could be unified with ".new_document .customfile:after".
Use "@extend .fa-refresh !optional" if the extend should be able to fail.

Extracted source (around line #514):
  &:after
      color: #bbb
      @extend .fa-refresh
      @include fa-icon
      display: none
      font-size: 36px

Any ideas? 
I tried rails g spina:install'ing demo and default on two separate projects but they both behave the same, throwing this error.
I tried specifying gem versions, but that does nothing.  Gem versions as of right now are:

Using rails 5.0.0
Using sass-rails 5.0.6
Using spina-template 0.2.14
Using spina 0.8.3

I appreciate any help, as I a really excited to getting something deployed!

**Comment by Bramjetten** [comment]
You should update spina-template. It's best to use the master branches if you want to use it with Rails 5 right now. 

Verstuurd vanaf mijn iPhone

**Comment by andrewgy8** [comment]
Thanks for the response!

Funny enough, I found the solution 10 min after I posted.  I updated my post with the fix for any one to reference.

Thanks for all the work,
Andrew

**Comment by germnor** [comment]
I resolved the issue erlingur was having by using the master branch. however, when I run 
`rails g spina:install` I receive the following error:

/home/vagrant/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- globalize (LoadError)
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
	from /vagrant/Spina/lib/spina/engine.rb:16:in `<top (required)>'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine/commands_tasks.rb:78:in `load_generators'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine/commands_tasks.rb:72:in `generate_or_destroy'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine/commands_tasks.rb:44:in `generate'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine/commands_tasks.rb:37:in `run_command!'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine/commands.rb:14:in `<top (required)>'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from script/rails:8:in `<main>'

Rails 5.0.0
Ruby 2.3.1 

I'm currently using the master branch of Spina-template as well.

**Comment by Bramjetten** [comment]
Did you add the master branch of Globalize?

Verstuurd vanaf mijn iPhone

**Comment by germnor** [comment]
I did add the master branch of Globalize.

`Using globalize 5.1.0 from git://github.com/globalize/globalize.git (at master@51aa34b)`

I'm running this on an precise64 Ubuntu 14.04 vagrant box if that makes a difference. 

What version of rails does this run most stably on? I can spin up another vagrant box and just develop on there. 

Thanks for the prompt feedback!

**Comment by germnor** [comment]
Alright, so I ran `gem install globalize`, which it ran successfully. However, now `rails g spina:install` is now raising a conflict error with the following: 

`/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2284:in 'raise_if_conflicts': Unable to activate globalize-5.0.1, because activerecord-5.0.0 conflicts with activerecord (< 4.3, >= 4.2.0), activemodel-5.0.0 conflicts with activemodel (< 4.3, >= 4.2.0) (Gem::ConflictError)`

Just to try and sort out the conflict I ran `gem uninstall activerecord --version 4.2.7` and it returned with a notification that `globalize-5.0.1 depends on activerecord (< 4.3, >= 4.2.0)`

So I ran `gem uninstall activerecord --version 5.0.0` and this returned the following: 

`activemodel-serializers-xml-1.0.1 depends on activerecord (> 5.x)
rails-5.0.0 depends on activerecord (= 5.0.0)`

So it seems that `globalize-5.0.1` depends on an older version of activerecord while `rails-5.0.0` requires the newest version. 

Perhaps I am wrong. I'm newish to programming.

**Comment by adityashukla74** [comment]
I installed with Rails 5 on Mac OSX, when I run **rails s**  
rails aborted!
Don't know how to build task 's' (see --tasks)
/Users/adityashukla/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/Users/adityashukla/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/Users/adityashukla/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0/lib/rails/engine/commands_tasks.rb:39:in `run_command!'
/Users/adityashukla/.rvm/gems/ruby-2.3.1@global/gems/railties-5.0.0/lib/rails/engine/commands.rb:14:in `<top (required)>'
script/rails:8:in `require'
script/rails:8:in `<main>'
(See full trace by running task with --trace)

**Comment by Bramjetten** [comment]
@germnor You have to use the master branch. Globalize didn't update their gemspec for use with Rails 5 yet.

**Comment by ddkwing** [comment]
I am encountered the same issue，the same as @germnor，when I run rails g spina:install I receive the following error:
cannot load such file -- globalize (LoadError) 

here is my Gemfile.lock
GIT
  remote: git://github.com/globalize/globalize.git
  revision: 51aa34b34ef6b00b8e6e307ac9145eeffade833c
  specs:
    globalize (5.1.0)
      activemodel (>= 4.2, < 5.1)
      activerecord (>= 4.2, < 5.1)
      request_store (~> 1.0)

Thanks for the prompt feedback!

**Comment by alexives** [comment]
@Bramjetten it really looks like breadcrumbs_on_rails just isn't compatible with rails 5... Updating to the master branch on spina, spina template, breadcrumbs_on_rails, and globalize, and it still throws the same error that @germnor is reporting.

Looking at breadcrumbs_on_rails has a pull request to fix this [here](https://github.com/weppos/breadcrumbs_on_rails/pull/77), but it has failing tests.

**Comment by alexives** [comment]
Looks like adding `gem 'breadcrumbs_on_rails', github: 'seuros/breadcrumbs_on_rails', branch: 'patch-1'` to my gemfile seems to have fixed it. 

That's the branch for the patch I mentioned in the last comment. Though it does appear to solve this issue, It's not merged, and still in review, waiting for tests I guess. If you can't wait, that gem is an option, but it might be better to wait for that pull request to merge.

**Comment by ddkwing** [comment]
@alexives Thank you for the solution，it's worked.

**Comment by bjkeeton** [comment]
I had the same error today, but when I added `gem 'breadcrumbs_on_rails', github: 'seuros/breadcrumbs_on_rails', branch: 'patch-1'` to my gemfile and bundled, `rails g spina:install` ran and it led me through the user creation process. Thanks, @alexives! :)

**Comment by a-barbieri** [comment]
At the moment original Globalize gem doesn't work due to this problem.

```
undefined method `symbolize_keys!' for {"content"=>""}:ActiveSupport::HashWithIndifferentAccess Did you mean? symbolize_keys
```

Instead use DigitalReflow one untill issue is fixed.
```
gem 'globalize', github: 'digitalreflow/globalize'
gem 'spina-template', github: 'denkGroot/Spina-template'
gem 'spina', github: 'denkGroot/Spina'
```
