### ISSUE TITLE
Using Spina with default layout/application.html.erb

### ISSUE THREAD

**Issue by ghn** [denkGroot/Spina#233]
Hello again,

I'm trying to setup Spina in an existing application. It means I'm trying to display the generated content into my existing layout in `views/layouts/application.html.erb`

I saw in the code that default Spina layout is hardcoded to something like `views/layouts/{template_name}/application.html.haml`. So I changed this in spina code to render my layout --> it works (I thought I may create a PR so the user can choose which layout he wants). 

But then I have lots of other problems with route names, helpers etc.. that are not loader.

Anybody had similar issues or has implemented Spina into an existing app? any tip or advice welcome.

**Comment by lukaVarga** [comment]
Hi, I don't know whether you still need help with this, but just in case someone else might be having similar issues, here's the workaround I implemented.

First off, what I need is Spina controlled routes for every page, except a couple (including home page) which are not supposed to be edited via the CMS. The first thing I thus had to do is disable the root Spina route. You can do this by adding 'config.disable_frontend_routes = true' in your spina.rb file.
This, however, also disables all the other routes. I took a look at the Spina routes and added the needed frontend routes to my app route file. So I added:
 ```
 get '/:locale/*id' => 'pages#show', constraints: {locale: /#{Spina.config.locales.join('|')}/ }
  get '/:locale/' => 'home#index', constraints: {locale: /#{Spina.config.locales.join('|')}/ }
  get '/*id' => 'pages#show', as: "page", controller: 'pages', constraints: lambda { |request|
    !(Rails.env.development? && request.env['PATH_INFO'].starts_with?('/rails/') || request.env['PATH_INFO'].starts_with?("/#{Spina.config.backend_path}") || request.env['PATH_INFO'].starts_with?('/attachments/'))
  }
```
home#index is my controller (I don't want my index page to be controllable via CMS). So that was changed from pages#homepage. Obviously, none of these controllers are in the Spina domain anymore, so I had to create my own Pages controller (which is something I needed, as I wanted to make use of the already existing before_actions I am using which are needed to provide some data based on which some fundamental components are built and did not want to make any changes to the Spina source code itself). 

You don't really need to do an awful lot here, just add the private methods in Spina's application_controller and add 'include Spina::Frontend' (so you can make use of different templates) in your custom controller and that's it. Vóila.

Next up - getting the views/layouts/{template_name}/application.html.haml to be the same as views/layouts/application.html.erb. First change the .haml to .erb. Then delete everything and just add
`<%= render template: 'layouts/application' %>` in the {template_name}/application.html.erb. Now you've got the same layout, same assets, etc, as you had previously :) Then just structure your default/pages/show.html.erb and style it properly and that's it. 

You can now define and use custom routes (without Spina's router interfering), you can run anything you need as you've got full control of what happens before it's being processed by Spina's code and you can use the default layouts/application.html.erb as a master layout without duplicating the code and without, in any way, modifying Spina's source code :)
